### ISSUE TITLE
demo data

### ISSUE THREAD

**Issue by HzjFirst** [OpenGeoVis/PVGeo-HDF5#2]
Can demo data be uploaded?

**Comment by banesullivan** [comment]
Luckily, I was cleaning up/archiving one of my old computers this past weekend... pretty sure if there are testing data, it's on that machine, so I will see what I can dig up while doing this.

Otherwise, this library was experimental at the time and I certainly cannot provide any support for this package moving forward.

For VTK/PyVista + HDF support, I highly encourage you to use Xarray  and PyVista-xarray: https://github.com/pyvista/pyvista-xarray

**Comment by banesullivan** [comment]
I've uploaded the data to Dropbox and made the link publicly accessible here: https://www.dropbox.com/sh/fb8ny080jca6pmc/AAB-gDU0JbChs-mVDqH70C5Xa?dl=0

**Comment by HzjFirst** [comment]
Thank you very much for your reply. I have already studied the library you recommended. But, I want to use NC data for particle effects in Paraview. Do you have any good suggestions?

**Comment by banesullivan** [comment]
The best I can recommend is to try the ParaView discourse for community help there: https://discourse.paraview.org/
